# Generated by Django 5.0.6 on 2024-11-25 00:23

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                help_text="Enter phone number with country code e.g. +23400000000",
                max_length=128,
                region=None,
            ),
        ),
    ]
