# Generated by Django 5.0.6 on 2024-07-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="course",
            field=models.CharField(
                choices=[
                    ("SEL", "--- Select Course ---"),
                    ("WEB", "Web development with Python"),
                    ("BOOT", "Python Bootcamp"),
                    ("MATH", "Python for Mathematics"),
                    ("GAME", "Game development with Python"),
                ],
                default="SEL",
                max_length=4,
            ),
        ),
    ]
