# Generated by Django 5.0.6 on 2024-08-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_customuser_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="date_added",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
