# Generated by Django 5.0.6 on 2024-11-25 01:46

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Enter phone number with country code e.g. +234XXXXXXXXXX",
                max_length=128,
                region=None,
            ),
        ),
    ]
