# Generated by Django 5.0.6 on 2024-08-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_customuser_age_customuser_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(help_text="Enter your Date of Birth"),
        ),
    ]
