# Generated by Django 5.0.6 on 2024-08-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_customuser_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(),
        ),
    ]
