# Generated by Django 5.0.6 on 2024-10-31 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_alter_contact_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.CharField(
                max_length=255, validators=[django.core.validators.EmailValidator()]
            ),
        ),
    ]
