# Generated by Django 5.0.6 on 2024-06-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date_added",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
