# Generated by Django 5.0.6 on 2024-08-01 23:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_post_image_alter_post_image2_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="date_added",
            new_name="date_modified",
        ),
        migrations.AddField(
            model_name="post",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
