# Generated by Django 5.0.6 on 2024-08-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_alter_post_image_alter_post_image2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, default="images/default.png", null=True, upload_to="images/"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image2",
            field=models.ImageField(
                blank=True, default="images/default.png", null=True, upload_to="images/"
            ),
        ),
    ]
