# Generated by Django 5.0.6 on 2024-08-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_alter_post_image_alter_post_image2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="static/images/default.png", upload_to="images/"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image2",
            field=models.ImageField(
                default="static/images/default.png", upload_to="images/"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
    ]
