# Generated by Django 5.0.6 on 2024-08-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_alter_post_image1_alter_post_image2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image1",
            field=models.ImageField(upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image2",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
