# Generated by Django 5.0.6 on 2024-11-08 21:21

import markdownfield.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0016_alter_post_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="body2_rendered",
            field=markdownfield.models.RenderedMarkdownField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="body_rendered",
            field=markdownfield.models.RenderedMarkdownField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=markdownfield.models.MarkdownField(rendered_field="body_rendered"),
        ),
        migrations.AlterField(
            model_name="post",
            name="body2",
            field=markdownfield.models.MarkdownField(rendered_field="body2_rendered"),
        ),
    ]
