# Generated by Django 5.0.6 on 2024-12-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0019_alter_post_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="body2",
        ),
        migrations.RemoveField(
            model_name="post",
            name="body2_rendered",
        ),
        migrations.RemoveField(
            model_name="post",
            name="image2",
        ),
        migrations.RemoveField(
            model_name="post",
            name="imgname",
        ),
        migrations.RemoveField(
            model_name="post",
            name="imgname2",
        ),
        migrations.AddField(
            model_name="post",
            name="image_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
