# Generated by Django 5.0.6 on 2024-11-25 21:49

import markdownfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LearnDjango",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("last_updated", models.DateField(auto_now=True)),
                (
                    "main_text",
                    markdownfield.models.MarkdownField(
                        rendered_field="main_text_rendered"
                    ),
                ),
                ("main_text_rendered", markdownfield.models.RenderedMarkdownField()),
            ],
        ),
        migrations.CreateModel(
            name="LearnPython",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("last_updated", models.DateField(auto_now=True)),
                (
                    "main_text",
                    markdownfield.models.MarkdownField(
                        rendered_field="main_text_rendered"
                    ),
                ),
                ("main_text_rendered", markdownfield.models.RenderedMarkdownField()),
            ],
        ),
    ]
