# Generated by Django 5.0.6 on 2024-11-25 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="learndjango",
            options={"verbose_name_plural": "Django Tutorial"},
        ),
        migrations.AlterModelOptions(
            name="learnpython",
            options={"verbose_name_plural": "Python Tutorial"},
        ),
    ]
