# Generated by Django 5.0.6 on 2024-11-25 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0002_alter_learndjango_options_alter_learnpython_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="learndjango",
            options={
                "verbose_name": "Django Tutorial",
                "verbose_name_plural": "Django Tutorial",
            },
        ),
        migrations.AlterModelOptions(
            name="learnpython",
            options={
                "verbose_name": "Python Tutorial",
                "verbose_name_plural": "Python Tutorial",
            },
        ),
    ]
