# Generated by Django 5.0.6 on 2024-11-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0003_alter_learndjango_options_alter_learnpython_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="learndjango",
            name="author",
            field=models.CharField(default="wealth", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="learnpython",
            name="author",
            field=models.CharField(default="wealth", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="learndjango",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="learnpython",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
