# Generated by Django 5.2.4 on 2025-08-01 13:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_learndjango_author_learnpython_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learndjango',
            options={'ordering': ('date_created',), 'verbose_name': 'Django Tutorial', 'verbose_name_plural': 'Django Tutorial'},
        ),
        migrations.AlterModelOptions(
            name='learnpython',
            options={'ordering': ('date_created',), 'verbose_name': 'Python Tutorial', 'verbose_name_plural': 'Python Tutorial'},
        ),
        migrations.RenameField(
            model_name='learndjango',
            old_name='last_updated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='learnpython',
            old_name='last_updated',
            new_name='date_updated',
        ),
        migrations.AddField(
            model_name='learndjango',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learnpython',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='learndjango',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='learndjango',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='learnpython',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='learnpython',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
