# Generated by Django 5.2.4 on 2025-08-03 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_alter_learndjango_options_alter_learnpython_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learndjango',
            options={'ordering': ('-date_created',), 'verbose_name': 'Django Tutorial', 'verbose_name_plural': 'Django Tutorial'},
        ),
        migrations.AlterModelOptions(
            name='learnpython',
            options={'ordering': ('-date_created',), 'verbose_name': 'Python Tutorial', 'verbose_name_plural': 'Python Tutorial'},
        ),
    ]
